### ISSUE TITLE
f35b_elevator.txt missing

### ISSUE THREAD

**Issue by smoelle116** [erkooi/fusion360#1]
csv_timeline360.py is asking for f35b_elevator.txt, which is not in folder F35B.

**Comment by erkooi** [comment]
Thank you. I have added the file.

**Comment by smoelle116** [comment]
Hi Eric,you are welcome. Seems also movecopy.py is missing...Best regards,Stefan Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: erkooi ***@***.***> Datum: 28.08.24  19:08  (GMT+01:00) An: erkooi/fusion360 ***@***.***> Cc: Stefan ***@***.***>, Author ***@***.***> Betreff: Re: [erkooi/fusion360] f35b_elevator.txt missing (Issue #1) 
Thank you. I have added the file.

**Comment by smoelle116** [comment]
Hi Eric,

 

running:


python ..\\csv_timeline360.py -f ^
f35b_points.txt,^
f35b_pin_holes.txt,^
f35b_aileron.txt,^
f35b_vertical_stabilizer.txt,^
f35b_elevator.txt,^
f35b_printing_parts.txt,^
f35b_airplane.txt,^
f35b_csv.txt


 

I getting this message:

 


Write CSV files for timeline file f35b_elevator.txt
read_units_from_file_lines: mm (default)
read_parameters_from_file_lines: Read 0 parameters
Traceback (most recent call last):
  File "C:\Users\Nutzer\Documents\Fusion 360\scripts\fusion360-main\csv_timeline360.py", line 174, in <module>
    nofFiles += write_csv_files_for_timeline_file(timelineFilename)
  File "C:\Users\Nutzer\Documents\Fusion 360\scripts\fusion360-main\csv_timeline360.py", line 109, in write_csv_files_for_timeline_file
    fileLines = userparameters.replace_parameters_in_file_lines(fileLines, parametersDict)
  File "C:\Users\Nutzer\Documents\Fusion 360\scripts\fusion360-main\userparameters.py", line 132, in replace_parameters_in_file_lines
    value = _eval_expression(pEntry)
  File "C:\Users\Nutzer\Documents\Fusion 360\scripts\fusion360-main\userparameters.py", line 247, in _eval_expression
    code = compile(expression, '<string>', 'eval')
  File "<string>", line 1
    $txTailEnd</div>
    ^
SyntaxError: invalid syntax


 

Best regards,

Stefan


 
 

Gesendet: Mittwoch, 28. August 2024 um 19:07 Uhr
Von: "erkooi" ***@***.***>
An: "erkooi/fusion360" ***@***.***>
Cc: "Stefan" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [erkooi/fusion360] f35b_elevator.txt missing (Issue #1)


 

Thank you. I have added the file.

**Comment by erkooi** [comment]
Hi Stefan,

I have added the missing movecopy.py file. If I now clone the repository from github, then csv_timeline360.py can generate all CSV files, and in Fusion360 I can run the DesignCSV script to generate the design in Fusion360. Can you print what is in fileLines ?

I cannot reproduce the error with $txTailEnd in f35b_elevator.txt. On my PC with this fresh clone from github it does run OK. The $txTailEnd is the first parameter in the f35b_elevator.txt file, and it looks like it did not get replaced, because the $txTailEnd is still there in the expression. Furthermore read_parameters_from_file_lines: Read 0 parameters, so there something goes wrong earlier. I think I need some more information to trace this error further. 

It is strange, because e.g. f35b_aileron.txt also contains parameters, and that file was parsed ok apparently, right?

PS: To create CSV files for only one txt file you can do: python ..\csv_timeline360.py -f f35b_elevator.txt

Greetings,
Eric

**Comment by smoelle116** [comment]
Hi Eric,

 

I cloned the repositiry again and works like a charm.  There are no error messages, I was able to extract 328 CSV with no issues.  Also I could repeat all ypur excercises you demonstrated in your video without any problems.   Excellent work!

 

What airfoil did you use in the model?  I looks like the airfoil is suitable for a model and not too thin.

 

 

Best regards,

Stefan

 
 

Gesendet: Donnerstag, 29. August 2024 um 21:56 Uhr
Von: "erkooi" ***@***.***>
An: "erkooi/fusion360" ***@***.***>
Cc: "Stefan" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [erkooi/fusion360] f35b_elevator.txt missing (Issue #1)


 

Hi Stefan,

I have added the missing movecopy.py file. If I now clone the repository from github then csv_timeline360.py can generate all CSV files and in Fusion360 I can run the DesignCSV script to generate the design in Fusion360.

I cannot reproduce the error with $txTailEnd in f35b_elevator.txt, on my PC with this fresh clone from github it does run OK. The $txTailEnd is the first parameter in the txTailEnd.txt file, and it looks like it did not get replaced, because the $txTailEnd is still there in the expression. I think I need some more information to trace this error further. Can you for example in csv_timeline360.py between lines:

parametersDict = userparameters.read_parameters_from_file_lines(fileLines)
fileLines = userparameters.replace_parameters_in_file_lines(fileLines, parametersDict)


put the line:

userparameters.print_parameters_dict(parametersDict)


to see what is in the parametersDict and whether txTailEnd is there. It is strange, because the e.g. f35b_aileron.txt also contains parameters, and that file was parced ok apparently, right?

PS: To create CSV files for only one txt file you can do: python ..\csv_timeline360.py -f f35b_elevator.txt

Greetings,
Eric

**Comment by erkooi** [comment]
That is good to hear that it now works.

The airfoil is indeed for a model. It is a NACA-1408 profile, see description in my F35b airplane youtube video. I created profiles along the wing with the script airfoils.py that is also in this repository. I made this airfoils.py script to be able to define other coordinates along the profile, that I then can use in the CSV files, to be able to twist the wing and to give the tail side of the wing some width > 0 so that it is more robust to e.g. 3D print.

**Comment by smoelle116** [comment]
Hi Eric,

 

understand.  So the wing already comes with a washout and the tip of the wing is pointing a bit downward?  

 

I also guess this frame is for a 120mm EDF, since the opening for the nozzle is almost 130mm in diameter.


 

 

Best regards,

Stefan

 

Gesendet: Freitag, 30. August 2024 um 14:06 Uhr
Von: "erkooi" ***@***.***>
An: "erkooi/fusion360" ***@***.***>
Cc: "Stefan" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [erkooi/fusion360] f35b_elevator.txt missing (Issue #1)


 

That is good to hear that it now works.

The airfoil is indeed for a model. It is a NACA-1408 profile, see description in my F35b airplane youtube video. I created profiles along the wing with the script airfoils.py that is also in this repository. I made this airfoils.py script to be able to define other coordinates along the profile, that I then can use in the CSV files, to be able to twist the wing and to give the tail side of the wing some width > 0 so that it is more robust to e.g. 3D print.
